proc ds2;
	data _null_;
		declare package &prglib..rumprg_SCB_FODDA fodda();
		method run();
			fodda.run();
		end;
	enddata;
run;quit;
proc ds2;
	data _null_;
		declare package &prglib..rumprg_SCB_flyttning68 bef68();
		method run();
			bef68.run();
		end;
	enddata;
run;quit;
proc ds2;
	data _null_;
		declare package &prglib..rumprg_SCB_flyttning97 bef97();
		method run();
			bef97.run();
		end;
	enddata;
run;quit;
proc ds2;
	data _null_;
		declare package &prglib..rumprg_SCB_Doda doda();
		method run();
			doda.run();
		end;
	enddata;
run;quit;
proc ds2;
	data _null_;
		declare package &prglib..rumprg_SCB_befolkningNy befNy();
		method run();
			befNy.run();
		end;
run;quit;
proc ds2;
	data _null_;
		dcl package &prglib..rumprg_SCB_befolkning bef();
		method run();
			bef.run();
		end;
	enddata;
run;quit;
proc ds2;
	data _null_;
		dcl package &prglib..rumprg_SCB_NYBYGGNATION nybygg();
		dcl package &prglib..rumprg_SCB_RflyttLan_hist RflyttLan_hist();
		method run();
			nybygg.run();
			RflyttLan_hist.run();
		end;
	enddata;
run;quit;

%rummac_read_Rikt_Kommunflytt;
run;
